### ISSUE TITLE
Fault make highligh-pointer

### ISSUE THREAD

**Issue by Dener-Garcia** [swillner/highlight-pointer#10]
Hello, i trying make my own highlight-pointer following your instructions but i receive a fault in terminal taking:

cc highlight-pointer.c -o highlight-pointer -flto -O3 -Wall -Wextra -Wshadow -std=c99 -lX11 -lXext -lXfixes -lXi
In file included from highlight-pointer.c:31:
/usr/include/X11/Xlib.h:38:10: fatal error: sys/types.h: No such file or directory
   38 | #include <sys/types.h>
      |          ^~~~~~~~~~~~~
compilation terminated.

if you can help please 

![fault-make-pointer](https://user-images.githubusercontent.com/107416682/177017151-532472cc-0682-4465-9a10-a43b00cb451a.jpg)

**Comment by swillner** [comment]
hi. looks like you are missing some standard library headers. Try to install them using `sudo apt-get install build-essential` (or just `sudo apt-get install libc6-dev` for this one particular library)

**Comment by Dener-Garcia** [comment]
Thanks for your help.
i can with this commands:

sudo apt-get install libc6-dev
sudo apt-get install build-essential
sudo apt install libx11-dev
sudo apt install libxi-dev
